# Generated by Django 5.0.2 on 2024-03-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifinder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='author',
            field=models.CharField(max_length=65),
        ),
    ]
