# Generated by Django 5.0.3 on 2024-03-22 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifinder', '0003_alter_objeto_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
