# Generated by Django 5.0.7 on 2024-07-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifinder', '0004_alter_item_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='author',
            new_name='Autor',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='date',
            new_name='Data',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='Descrição',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='is_published',
            new_name='Publicada',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='title',
            new_name='Título',
        ),
    ]
