# Generated by Django 5.0.7 on 2024-07-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifinder', '0005_rename_author_item_autor_rename_date_item_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Status',
            field=models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado')], default='perdido', max_length=10),
        ),
    ]
