# Generated by Django 5.0.7 on 2024-07-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifinder', '0006_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Status',
            field=models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado')], max_length=10),
        ),
    ]
