# Generated by Django 5.0.7 on 2024-07-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifinder', '0007_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Descrição',
            field=models.TextField(max_length=165),
        ),
    ]
