# Generated by Django 5.0.7 on 2024-07-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifinder', '0008_alter_item_descrição'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Imagem',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
