# Generated by Django 5.0.7 on 2024-07-12 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifinder', '0009_item_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Imagem',
            field=models.ImageField(blank=True, default='fallback.png', upload_to=''),
        ),
    ]
