# Generated by Django 5.0.7 on 2024-07-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifinder', '0010_alter_item_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Imagem',
            field=models.ImageField(upload_to=''),
        ),
    ]
