# Generated by Django 5.0.6 on 2024-07-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifinder', '0011_alter_item_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Devolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='Imagem',
            field=models.ImageField(max_length=300, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='Status',
            field=models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado'), ('devolvido', 'Devolvido')], max_length=10),
        ),
    ]
