# Generated by Django 5.1 on 2024-08-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifinder', '0012_item_devolvido_alter_item_imagem_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='Status',
            field=models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado')], max_length=10),
        ),
    ]
