# Generated by Django 5.1 on 2024-08-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ifinder', '0013_alter_item_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Publicada',
            new_name='Publicado',
        ),
    ]
